# Generated by Django 3.1 on 2021-11-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-date']},
        ),
    ]
