# Generated by Django 3.1 on 2021-11-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newsletter', '0003_auto_20211111_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='user_email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
