# Generated by Django 3.1 on 2021-11-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.IntegerField(choices=[(0, 'Collaboration'), (1, 'Meeting'), (2, 'Consultancy'), (3, 'Gratitude')], default=3),
        ),
    ]
