# Generated by Django 3.2.7 on 2021-12-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Collaboration', 'Collaboration'), ('Meeting', 'Meeting'), ('Consultancy', 'Consultancy'), ('Gratitude', 'Gratitude')], default='Collaboration', max_length=200),
        ),
    ]
