# Generated by Django 3.2.7 on 2021-12-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0004_alter_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
